import { CSSProperties } from 'react';

export const styling = {
	chat: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'space-between',
		width: '20vw',
		minWidth: '300px',
		maxWidth: '600px',
		height: '85vh',
		maxHeight: '1000px',
		border: '1px solid black',
		borderRadius: '5px',
		padding: '2px',
		boxSizing: 'border-box',
		overflow: 'hidden',
		backgroundColor: '#0093E9',
		backgroundImage: 'linear-gradient(160deg, #0093E9 0%, #80D0C7 100%)',
		color: '#fff',
	},
	header: { height: '8%', margin: '4px' },
	chats: {
		overflowY: 'scroll',
		height: '80%',
		width: '100%',
		padding: '2px',
		boxSizing: 'border-box',
	},
	myChat: {
		backgroundColor: '#00bae9',
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		padding: '2px 4px',
		boxSizing: 'border-box',
		margin: '2px 0',
		border: '1px solid',
		borderColor: '#ffffffa9',
	},
	otherChat: {
		backgroundColor: '#0080e9',
		display: 'flex',
		flexDirection: 'row-reverse',
		alignItems: 'center',
		justifyContent: 'space-between',
		padding: '2px 4px',
		boxSizing: 'border-box',
		margin: '2px 0',
		border: '1px solid',
		borderColor: '#ffffffa9',
	},
	chatAvatar: {
		width: '30px',
		height: '30px',
		maxHeight: '90%',
		maxWidth: '30%',
		borderRadius: '50%',
		margin: '2px',
		padding: 0,
	},
	avatarAndName: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		width: '30%',
	},
	sender: {
		fontSize: '0.8rem',
		whiteSpace: 'nowrap',
		maxWidth: '70%',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		margin: 0,
		padding: 0,
	},
	message: {
		width: '70%',
	},
	form: {
		width: '100%',
		display: 'flex',
		margin: '2px 0',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	input: {
		width: '90%',
		margin: '0 4px',
		boxSizing: 'border-box',
		color: 'white',
	},
	fab: {
		backgroundColor: '#0093E9',
		backgroundImage: 'linear-gradient(160deg, #0093E9 0%, #80D0C7 100%)',
		color: 'white',
		border: '1px solid',
		borderColor: '#ffffffa9',
	},
} as { [key: string]: CSSProperties };
