---
name: STAGING - Continuous Deployment

on:
    push:
        # Run workflow every time something is pushed to the main branch
        branches:
            - 'feat/**'
            - nextRefactor
    # allow manual triggers for now too
    workflow_dispatch:
        manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push frontend
              uses: docker/build-push-action@v2
              with:
                  context: '{{defaultContext}}:frontend'
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/multiminerfrontendstaging:latest
                  cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/multiminerfrontendstaging:multiminerfrontendcachestaging
                  cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/multiminerfrontendstaging:multiminerfrontendcachestaging,mode=max
                  secrets: |
                      "AUTH0_SECRET=${{secrets.AUTH0_SECRET}}"
                      "AUTH0_BASE_URL=${{secrets.AUTH0_BASE_URL_STAGING}}"
                      "AUTH0_ISSUER_BASE_URL=${{secrets.AUTH0_ISSUER_BASE_URL}}"
                      "AUTH0_CLIENT_ID=${{secrets.AUTH0_CLIENT_ID}}"
                      "AUTH0_CLIENT_SECRET=${{secrets.AUTH0_CLIENT_SECRET}}"
                      "NEXT_PUBLIC_BACKEND_URL=${{secrets.NEXT_PUBLIC_BACKEND_URL_STAGING}}"
                      "NEXT_PUBLIC_ENVIRONMENT=${{secrets.NEXT_PUBLIC_ENVIRONMENT_STAGING}}"

            - name: Build and push backend
              uses: docker/build-push-action@v2
              with:
                  context: '{{defaultContext}}:backend'
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/multiminerbackendstaging:latest
                  cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/multiminerbackendstaging:multiminerbackendcachestaging
                  cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/multiminerbackendstaging:multiminerbackendcachestaging,mode=max
                  secrets: |
                      "MONGODB_PASSWORD=${{secrets.MONGODB_PASSWORD}}"
                      "MONGODB_USERNAME=${{secrets.MONGODB_USERNAME}}"

            - name: Configure SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/multiminer.key
                  chmod 600 ~/.ssh/multiminer.key
              env:
                  SSH_KEY: ${{ secrets.SSH_KEY }}

            - name: Deploy to server
              # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
              run: >
                  ssh $SSH_USER@$SSH_HOST
                  -i ~/.ssh/multiminer.key -o StrictHostKeyChecking=no
                  '/multiminer/deploy.sh'
              env:
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_HOST: ${{ secrets.SSH_HOST_STAGING }}
